/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package Hotel;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.*;

public class VentanaPrincipal extends JFrame implements ActionListener {
    private Container contenedor;
    private JMenuBar barraMenu;
    private JMenu menuOpciones;
    private JMenuItem itemMenu1;
    private JMenuItem itemMenu2;
    private Hotel hotel;
    
    public VentanaPrincipal(Hotel hotel) {
        this.hotel = hotel;
        inicio();
        setTitle("Hotel");
        setSize(280, 380);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setResizable(false);
    }
    
    private void inicio() {
        contenedor = getContentPane();
        contenedor.setLayout(null);
        
        barraMenu = new JMenuBar();
        menuOpciones = new JMenu("Menú");
        itemMenu1 = new JMenuItem("Consultar habitaciones");
        itemMenu2 = new JMenuItem("Salida de huéspedes");
        
        menuOpciones.add(itemMenu1);
        menuOpciones.add(itemMenu2);
        barraMenu.add(menuOpciones);
        setJMenuBar(barraMenu);
        
        itemMenu1.addActionListener(this);
        itemMenu2.addActionListener(this);
        
        System.out.println("VentanaPrincipal inicializada correctamente");
    }
    
    @Override
    public void actionPerformed(ActionEvent evento) {
        System.out.println("Evento detectado: " + evento.getSource());
        
        if (evento.getSource() == itemMenu1) {
            System.out.println("Abriendo VentanaHabitaciones...");
            try {
                VentanaHabitaciones ventanaHabitaciones = new VentanaHabitaciones(hotel);
                ventanaHabitaciones.setVisible(true);
                System.out.println("VentanaHabitaciones creada exitosamente");
            } catch (Exception e) {
                System.err.println("Error al crear VentanaHabitaciones: " + e.getMessage());
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, 
                    "Error al abrir ventana: " + e.getMessage(), 
                    "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        
        if (evento.getSource() == itemMenu2) {
            System.out.println("Abriendo diálogo de salida...");
            try {
                String númeroHabitación = JOptionPane.showInputDialog(null,
                    "Ingrese número de habitación", "Salida de huéspedes",
                    JOptionPane.QUESTION_MESSAGE);
                
                if (númeroHabitación == null) {
                    System.out.println("Usuario canceló");
                    return;
                }
                
                int número = Integer.valueOf(númeroHabitación);
                System.out.println("Número ingresado: " + número);
                
                if (número < 1 || número > 10) {
                    JOptionPane.showMessageDialog(this,
                        "El número de habitación debe estar entre 1 y 10",
                        "Mensaje", JOptionPane.INFORMATION_MESSAGE, null);
                } else if (hotel.buscarHabitaciónOcupada(número)) {
                    System.out.println("Habitación ocupada, abriendo VentanaSalida...");
                    VentanaSalida ventanaSalida = new VentanaSalida(hotel, número);
                    ventanaSalida.setVisible(true);
                } else {
                    System.out.println("Habitación NO ocupada");
                    JOptionPane.showMessageDialog(this,
                        "La habitación ingresada no ha sido ocupada. Debe registrar un huésped primero.",
                        "Mensaje", JOptionPane.INFORMATION_MESSAGE, null);
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null,
                    "Debe ingresar un número válido",
                    "Error", JOptionPane.ERROR_MESSAGE);
            } catch (Exception e) {
                System.err.println("Error: " + e.getMessage());
                e.printStackTrace();
                JOptionPane.showMessageDialog(null,
                    "Error: " + e.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
